//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emplySoftware.DatabaseSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatUsers
    {
        public int chatID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual chatList chatList { get; set; }
        public virtual User User { get; set; }
    }
}
